service: lambda-layer-sharp
frameworkVersion: ">=1.34.0 <2.0.0"
provider:
  name: aws
  stage: "${opt:stage,'dev'}"
  stackName: lambda-layer-sharp-${self:provider.stage}
layers:
  NodeSharp:
    name: lambda-layer-node-sharp-${self:provider.stage}
    path: layer
    package:
      include:
        - node_modules/**
    description: sharp@0.23.4
    compatibleRuntimes:
      - nodejs12.x
    licenseInfo: Apache License 2.0
    retain: true
